### PR TITLE
Add a few additional dgn and decoders

### PR DESCRIPTION
**Pull request by spbrogan**
- WATER_PUMP_STATUS
  - WATER_PUMP_COMMAND
  - WATERHEATER_COMMAND2
  - CIRCULATION_PUMP_STATUS
  - CIRCULATION_PUMP_COMMAND

### CODE REVIEW

**Comment by spbrogan** [comment]
@linuxkidd  - Do you add these manually or did you write some sort of script to parse the rv-c spec?

**Review by linuxkidd — APPROVED** [review]

**Comment by linuxkidd** [comment]
Hi @spbrogan  Thanks!

The ones I've done were all by hand.  @greendog99 did a bunch of this work initially, and I'm not sure if he hand wrote them, or created them programmatically.

I'll merge this in.  Thanks again!

**Comment by greendog99** [comment]
If you mean converting the rv-c PDF file into the yaml file, yeah, that was all by hand. Sometimes traumatically so :-)

**Comment by spbrogan** [comment]
> If you mean converting the rv-c PDF file into the yaml file, yeah, that was all by hand. Sometimes traumatically so :-)

Thanks for the info.

**Pull request merged**
